### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Vladian-Diac-JCMaxwell-4Bi** [Francesco-Criniti-JCMaxwell-4BI/Registro-Di-Classe#16]
Il progetto si può ritenere concluso, solo che ci sono ancora alcuni BUG da risolvere. Il programma è funzionante ma certe volte su alcuni aspetti da ancora problemi ( sono problemi piccoli, ma si possono risolvere)

**Comment by Francesco-Criniti-JCMaxwell-4BI** [comment]
ok allora passiamo il compito a raffaele che ci farà da beta-tester, uno volta fatto girare un paio di volte riusciremo a capire bene i bug da risolvere e come risolverli

**Comment by Raffaele-Santoro-4BiJCMaxwell** [comment]
va bene
